name: Deploy GerenciadorDeProdutos

on:
  push:
    branches:
      - master  # Altere para o branch correto caso necessário
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Altere conforme a versão do seu projeto

      - name: Restaurar pacotes
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build --configuration Release --no-restore

      - name: Executar testes unitários
        run: dotnet test --no-restore --verbosity normal

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Publicar aplicação
        run: dotnet publish -c Release -o out

      - name: Enviar artefatos para GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: out
